# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# -----
image: python:3.6.1

pipelines:
  default:
    - step:
        script:
          - pip install -U tox
          - pip --version
          - tox --version
          - tox -r -e py36,cython

image: python:3.5.2

pipelines:
  default:
    - step:
        script:
          - pip install -U tox
          - pip --version
          - tox --version
          - tox -r -e py27,py35,cython
